            anonymous:
              - job-discover
              - job-read
              - job-extended-read
              - job-workspace
            lsandov1:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
            fboudra:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
