            anonymous:
              - job-discover
              - job-read
              - job-extended-read
              - job-workspace
            fboudra:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
              - run-update
            lsandov1:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
              - run-update
            pfalcon:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
              - run-update
            trusted-firmware-ci*trusted-firmware-A-OpenCI-Users:
              - job-read
              - job-extended-read
              - job-build
              - job-cancel
